name: Build Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container: electronuserland/builder:wine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:linux --if-present

      - name: Upload build to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.pacman

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-artifacts
          path: dist/

  build-macos:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac --if-present

      - name: Upload build to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.dmg
            dist/*.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-latest-artifacts
          path: dist/
